name: Blender 3.6 Docker Build and Push

on:
  push:
    paths:
      - blender-36.Dockerfile
      - .github/workflows/blender-36-docker-image.yml

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Convert repository_owner to lowercase
        id: convert_owner
        run: echo "owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: blender-36.Dockerfile
          platforms: linux/amd64  #,linux/arm64  # Customize as needed
          push: true
          tags: ghcr.io/${{ steps.convert_owner.outputs.owner }}/blender:3.6
          cache-from: type=registry,ref=ghcr.io/${{ steps.convert_owner.outputs.owner }}/blender:3.6-buildcache
          cache-to: type=inline
