name: Blender PyTorch Ubuntu 4.5 LTS Docker Build and Push

on:
  push:
    paths:
      - blender-torch-45.Dockerfile
      - .github/workflows/blender-torch-45-docker-image.yml

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          overprovision-lvm: 'true'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Convert repository_owner to lowercase
        id: convert_owner
        run: echo "owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: blender-torch-45.Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/${{ steps.convert_owner.outputs.owner }}/blender:4.5-torch
          cache-from: type=registry,ref=ghcr.io/${{ steps.convert_owner.outputs.owner }}/blender:4.5-torch-buildcache
          cache-to: type=registry,ref=ghcr.io/${{ steps.convert_owner.outputs.owner }}/blender:4.5-torch-buildcache,mode=max
